### ISSUE TITLE
Thorium Nova does not automatically download the default plugin

### ISSUE THREAD

**Issue by parracodea** [Thorium-Sim/thorium-nova#611]
**Describe the bug**

When running Thorium Nova for the first time, the application gets stuck a screen that says "Thorium Nova is Loading". Running the application in PowerShell reveals that there are no plugins installed.

**To Reproduce** Steps to reproduce the behavior:

1. Open Powershell
2. Run `Thorium Nova.exe`
3. The following output appears:
```
file:///C:/additional-folders-here/Thorium-Nova-1.0.0-alpha.12-win/resources/app/dist/index.js:516876  
throw new Error("Thorium Nova requires at least one plugin to run.");  
^

Error: Thorium Nova requires at least one plugin to run.  
at #loadPlugins ([file:///C:/additional-folders-here/Thorium-Nova-1.0.0-alpha.12-win/resources/app/dist/index.js:516876:13)](file:///C:/additional-folders-here/Thorium-Nova-1.0.0-alpha.12-win/resources/app/dist/index.js:516876:13%29 "file:///C:/additional-folders-here/Thorium-Nova-1.0.0-alpha.12-win/resources/app/dist/index.js:516876:13)")

Node.js v18.18.2

(node:13416) UnhandledPromiseRejectionWarning: TypeError: fetch failed  
at Object.fetch (node:internal/deps/undici/undici:11372:11)  
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
at async yI ([file:///C:/additional-folders-here/Thorium-Nova-1.0.0-alpha.12-win/resources/app/dist/electron.js:120:34106)](file:///C:/additional-folders-here/Thorium-Nova-1.0.0-alpha.12-win/resources/app/dist/electron.js:120:34106%29 "file:///C:/additional-folders-here/Thorium-Nova-1.0.0-alpha.12-win/resources/app/dist/electron.js:120:34106)")  
at async App.&lt;anonymous&gt; ([file:///C:/additional-folders-here/Thorium-Nova-1.0.0-alpha.12-win/resources/app/dist/electron.js:120:36268)](file:///C:/additional-folders-here/Thorium-Nova-1.0.0-alpha.12-win/resources/app/dist/electron.js:120:36268%29 "file:///C:/additional-folders-here/Thorium-Nova-1.0.0-alpha.12-win/resources/app/dist/electron.js:120:36268)")  
(Use \`Thorium Nova --trace-warnings ...\` to show where the warning was created)  
(node:13416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag \`--unhandled-rejections=strict\` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 39)
```

**Expected behavior**

The default plugin should be downloaded. 
However, `C:\Users\user-home-folder\Documents\thorium-nova\db.yml` and `C:\Users\user-home-folder-here\Documents\thorium-nova\plugins` (empty folder) were created.

**Additional context**

- Operating System: Windows 10
- Thorium Nova Version: Thorium-Nova-1.0.0-alpha.12-win

**Comment by megadakkajet** [comment]
getting the same issue here.

**Comment by alexanderson1993** [comment]
This should be resolved in Alpha 15
